### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by nerd-qp** [yrp604/rappel#8]
➜  rappel git:(master) make ARCH=x86
                
/usr/bin/ld: cannot find -ledit
collect2: error: ld returned 1 exit status
Makefile:52: recipe for target 'bin/rappel' failed
make: *** [bin/rappel] Error 1

OS: Linux 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
cc: gcc

**Comment by yrp604** [comment]
Did you have libedit-dev installed?

**Comment by nerd-qp** [comment]
Yes, I have.

libedit-dev is already the newest version (3.1-20150325-1ubuntu2).

thanks!

BTW: this result is produced by a virtual machine
uname -v: Linux precise32 3.2.0-126-generic-pae #169-Ubuntu SMP Fri Mar 31 14:43:09 UTC 2017 i686 i686 i386 GNU/Linux
gcc -v: gcc version 4.7.3 (Ubuntu/Linaro 4.7.3-2ubuntu1~12.04) 

ptrace.c: 100:4: warning: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'long unsigned int' [-Wformat]
ptrace.c: In function 'ptrace_launch':
ptrace.c:131:2: error: 'PTRACE_O_EXITKILL' undeclared (first use in this function)
ptrace.c:131:2: note: each undeclared identifier is reported only once for each function it appears in
ptrace.c: At top level:
cc1: warning: unrecognized command line option "-Wno-gnu-empty-initializer" [enabled by default]
make: *** [obj/ptrace.o] Error 1

Actually I can use -ledit on empty main. Maybe compiling using 64bits library with -m32 can be troubling?

**Comment by yrp604** [comment]
I was able to reproduce and fix your problem by installing libedit-dev:i386 (dpkg --add-architecture i386). Could you try this?

Unfortunately PTRACE_O_EXITKILL requires linux 3.8+, so it doesn't look like rappel will work on 3.2

**Comment by nerd-qp** [comment]
Many thanks!!! It worked!
